version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: postgres_container2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tyba_test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data: